#!/bin/sh

start() {
	/sbin/modprobe soundcore
	/sbin/modprobe snd
	/sbin/modprobe snd_timer
	/sbin/modprobe snd_pcm
	/sbin/modprobe snd_pcm_dmaengine
	/sbin/modprobe snd_soc_core
	/sbin/modprobe out_to_pins
	/sbin/modprobe snd_soc_simple_card_utils
	/sbin/modprobe snd_soc_audio_graph_card
	/sbin/modprobe snd_soc_stm32_sai
	/sbin/modprobe snd_soc_stm32_sai_sub
	/sbin/modprobe cdc-acm
}

stop() {
	echo "yes" > /dev/null
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
