#!/bin/sh
#
# Starts /etc/rc.load.
#

start() {
	printf "Stopping /etc/rc.load"
    /etc/rc.load start
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping /etc/rc.load"
    # /etc/rc.load stop
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
